package multiagentes;


/**
* multiagentes/ImagenesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from imagenes.idl
* jueves 10 de mayo de 2012 23H58' CDT
*/

abstract public class ImagenesHelper
{
  private static String  _id = "IDL:multiagentes/Imagenes:1.0";

  public static void insert (org.omg.CORBA.Any a, multiagentes.Imagenes that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static multiagentes.Imagenes extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (multiagentes.ImagenesHelper.id (), "Imagenes");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static multiagentes.Imagenes read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ImagenesStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, multiagentes.Imagenes value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static multiagentes.Imagenes narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof multiagentes.Imagenes)
      return (multiagentes.Imagenes)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      multiagentes._ImagenesStub stub = new multiagentes._ImagenesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static multiagentes.Imagenes unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof multiagentes.Imagenes)
      return (multiagentes.Imagenes)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      multiagentes._ImagenesStub stub = new multiagentes._ImagenesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
