package multiagentes;


/**
* multiagentes/ImagenesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from imagenes.idl
* jueves 10 de mayo de 2012 23H58' CDT
*/

public interface ImagenesOperations 
{
  void leer (String imagen);
  void BlancoNegro (String imagen);
  void AumentarBrillo (String imagen);
  void QuitarBrillo (String imagen);
} // interface ImagenesOperations
